print('=====================DESAFIO 2=====================')
print('Favor informar sua data de nascimento com 2 dígitos e 4 "DD,MM,AAAA"')
dia = input('Qual seu dia de nascimento?')
mes = input('Qual seu mes de nascimento?')
ano = input('Qual seu ano de nascimento?')
print('A sua data de nascimento é: ', dia, '/', mes, '/', ano, 'conforme o padrão: DD/MM/AAAA')
